[fix] account for breaking change in aws secretsiface (#72)
Generated from:
* make generate-mocks
* cd aws
* go generate

Source of issue:
https://github.com/aws/aws-sdk-go/commit/09f89e43e1bc1e647cd2bc83cf7cfb55c5be7fb3#diff-90d1f3d3c23c033ba5bfa8f99a0651bfR141

How I discovered the problem:
```
➜  aws-oidc git:(aku/parallelize-list-roles) ✗ make deps
go get -u ./...
# github.com/chanzuckerberg/go-misc/aws
../../../go/pkg/mod/github.com/chanzuckerberg/go-misc@v0.0.0-20200629193718-e3bb458e51a5/aws/client.go:77:37: cannot use mock (type *mocks.MockSecretsManagerAPI) as type secretsmanageriface.SecretsManagerAPI in field value:
	*mocks.MockSecretsManagerAPI does not implement secretsmanageriface.SecretsManagerAPI (missing ValidateResourcePolicy method)
make: *** [deps] Error 2
```